
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    output:
      ansi:
        enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/logger?useTimezone=true&serverTimezone=EST
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
